name: CI

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint & test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        cache-prefix: ${{ matrix.python-version }}
        version: '0.39.0'

    - name: Pin python-version ${{ matrix.python-version }}
      run: rye pin ${{ matrix.python-version }}

    - name: Install dependencies
      run: rye sync

    - name: Run lints
      run: rye run ci

    - name: Run tests with coverage
      run: rye run test

  # build:
  #   name: Build

  #   needs: lint-test

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       directory: ["api", "bot"]

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Login to Github Container Registry
  #     uses: docker/login-action@v3
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.GITHUB_TOKEN }}

  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v6
  #     with:
  #       context: ./${{ matrix.directory }}
  #       file: ./${{ matrix.directory }}/Dockerfile
  #       push: true
  #       cache-from: type=registry,ref=ghcr.io/xithrius/ordis/${{ matrix.directory }}:latest
  #       cache-to: type=inline
  #       tags: |
  #         ghcr.io/xithrius/ordis/${{ matrix.directory }}:${{ github.sha }}
  #         ghcr.io/xithrius/ordis/${{ matrix.directory }}:latest
  #       build-args: |
  #         git_sha=${{ github.sha }}
